sbt 2.x
scalacenter/sbt-scalafix pull request #440
Opened 2024-10-05 21:37 UTC by bjaglin

- [ ] https://github.com/sbt/sbt/issues/7707

2024-10-05 22:08 UTC, bjaglin commented on src/main/scala/scalafix/sbt/ScalafixEnable.scala
> -                    Seq(
This was picked as significant indentation by the compiler (and has been all along by scalafmt as scala3 is used everywhere as dialect), which was causing `latestAvailable`'s type to be recursive :shrug:

2025-03-09 17:26 UTC, bjaglin commented on build.sbt
> +      "2.0.0-SNAPSHOT"
```suggestion
      "2.0.0-M4"
```

2025-03-09 17:26 UTC, bjaglin commented on bin/test-release.sh
> +    --sbt-version 2.0.0-SNAPSHOT \
```suggestion
    --sbt-version 2.0.0-M4 \
```

2025-03-09 17:27 UTC, bjaglin commented on src/main/scala-3/scalafix/internal/sbt/Compat.scala
> +      .map(Classpaths.moduleIdJsonKeyFormat.read)
https://github.com/sbt/sbt/pull/7464/commits/34f9b7f54a09dab5eb220dcf174bd38576e551c2

2025-03-09 19:49 UTC, bjaglin commented on src/main/scala-3/scalafix/internal/sbt/Compat.scala
> +    toPath(attributed).toFile()
https://www.scala-sbt.org/2.x/docs/en/changes/migrating-from-sbt-1.x.html#migrating-classpath-type

2025-03-09 19:51 UTC, bjaglin commented on .github/workflows/ci.yml
> +      - run: sbt scalafixAll --check
enforcing scalafix in this PR mostly for ExplicitResultTypes, to have deterministic types from the beginning for the sbt 2.x artifact

2025-03-09 19:53 UTC, bjaglin commented on build.sbt
> +      "2.0.0-SNAPSHOT"
```suggestion
      "2.0.0-M4"
```

2025-03-09 20:26 UTC, bjaglin commented on .scalafix.conf
> +  targetDialect = Scala3
```
sbt:sbt-scalafix> show Compile/scalacOptions
...
[info] * -Xsource:3
```

https://github.com/sbt/sbt/pull/6664/commits/505492ed332bebfc92508c98378ad968b0ac22ee

2025-03-09 20:39 UTC, bjaglin commented on project/Dependencies.scala
> +    "org.scala-lang.modules" %% "scala-collection-compat" % "2.13.0"
helps getting rid of `import scala.collection.JavaConverters.*` mostly

2025-03-09 22:57 UTC, bjaglin commented on src/main/scala/scalafix/sbt/ScalafixPlugin.scala
> -    // workaround https://github.com/sbt/sbt/issues/3572 by invoking directly what Def.inputTaskDyn would via macro
https://github.com/sbt/sbt/issues/3572#issuecomment-2709115229

2025-03-10 19:57 UTC, bjaglin commented on .github/workflows/ci.yml
> +      - run: sbt "scalafixAll --check"
enforcing scalafix in this PR mostly for ExplicitResultTypes, to have deterministic types from the beginning for the sbt 2.x artifact

2025-03-12 20:39 UTC, bjaglin commented on src/main/scala/scalafix/sbt/ScalafixPlugin.scala
> +        Defaults.configSettings ++ SemanticdbPlugin.configurationSettings,
sbt 2.0.0-M4 rightfully detects `Scalafix / semanticdbTargetRoot` as unused, because the key is defined in Defaults but the plugin config settings were not applied. It doesn't hurt to trigger semanticdb on scalafix rules (for metals for example)...

2025-03-13 07:17 UTC, bjaglin commented on project/build.properties
> +sbt.version=2.0.0-M4
this currently breaks metals integration (even with BSP handled by sbt itself rather than metals) pending the follow-up of https://github.com/scalameta/metals/pull/7045 for metals

2025-03-13 07:25 UTC, bjaglin commented on .github/workflows/ci.yml
> +        scala: ["2.12"]
:warning:  sbt2 does not seem to start on CI windows
```
Run sbt ++2.12 test-skip-windows scripted
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
[error] Failed to start server : java.io.IOException: Cannot run program "C:/Program Files" (in directory "D:\a\sbt-scalafix\sbt-scalafix"): CreateProcess error=5, Access is denied
[error] failed to connect to server
```

2025-03-13 21:42 UTC, bjaglin commented on src/sbt-test/sbt-scalafix/basic/build.sbt
> +    logLines.exists(_.startsWith("[error] -import scala.concurrent.Future")),
for some weird reason, the lines have non-visible trailing characters when the scripted is run from sbt2 in JDK<21

2025-03-13 21:51 UTC, bjaglin commented on .github/workflows/ci.yml
> -          apps: sbt
the cs-install runner fails to start sbt2 on windows
```

Run sbt ++2.12 test-skip-windows scripted
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
[error] Failed to start server : java.io.IOException: Cannot run program "C:/Program Files" (in directory "D:\a\sbt-scalafix\sbt-scalafix"): CreateProcess error=5, Access is denied
[error] failed to connect to server
```

2025-03-13 23:21 UTC, bjaglin commented on .github/workflows/ci.yml
> -        shell: bash
```

6s
Run sbt -v '++2.12.x test-skip-windows scripted'
  sbt -v '++2.12.x test-skip-windows scripted'
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    COURSIER_BIN_DIR: C:\Users\runneradmin\cs\bin
[sbt_options] declare -a sbt_options=()
[debug] running native client
# Executing command line:
"/c/Program Files (x86)/sbt/bin/sbtn-x86_64-pc-win32.exe"
"--sbt-script=/c/Program%20Files (x86)/sbt/bin/sbt"
-v
"++2.12.x test-skip-windows scripted"

[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
[error] Failed to start server : java.io.IOException: Cannot run program "C:/Program Files" (in directory "D:\a\sbt-scalafix\sbt-scalafix"): CreateProcess error=5, Access is denied
[error] failed to connect to server
```

2025-03-13 23:54 UTC, bjaglin commented on .github/workflows/ci.yml
> -        shell: bash
https://github.com/sbt/sbt/issues/8064

2025-03-21 13:31 UTC, bjaglin commented on src/sbt-test/sbt-scalafix/relax-scalacOptions/test
> -> clean
https://eed3si9n.com/sbt-remote-cache/#case-study-compile-task

> This shows that even after `clean`, which currently cleans the target directory, `compile` is cached

2025-03-21 16:52 UTC, bjaglin commented on project/plugins.sbt
> +//addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.9.3")
:warning:  pending cross-publishing to 2.0.0-M4

2025-03-21 17:00 UTC, bjaglin commented on .github/workflows/ci.yml
> +        run: rm -rf src/sbt-test/skip-java17+/scalafixResolvers
⚠️ pending https://github.com/Philippus/sbt-dotenv/issues/242

2025-03-21 17:40 UTC, bjaglin commented on build.sbt
> +    case _ => false
There is some contamination across scripted when batching in sbt 2.x
- `skip-windows/caching` -> `java.lang.ClassNotFoundException: LintAllPlugin$`
- `skip-sbt1.4/cross-build-scala3` -> `java.lang.ClassNotFoundException: LintAllPlugin$`
-`sbt-scalafix/scalafixOnCompile` -> `java.lang.ClassNotFoundException: FatalWarningsPlugin$`

2025-03-22 08:59 UTC, Philippus requested changes

2025-03-22 08:59 UTC, Philippus commented on src/sbt-test/skip-java17+/scalafixResolvers/project/plugins.sbt
> +addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "3.1.1")
the groupId has changed some years ago to `nl.gn0s1s`: https://github.com/Philippus/sbt-dotenv/?tab=readme-ov-file#installation

2025-03-22 09:03 UTC, bjaglin commented on src/sbt-test/skip-java17+/scalafixResolvers/project/plugins.sbt
> +addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "3.1.1")
yep, just saw it as well, thanks for looking into it here!

2025-03-22 19:13 UTC, bjaglin commented on src/sbt-test/skip-java17+/scalafixResolvers/project/plugins.sbt
> +addSbtPlugin("nl.gn0s1s" %% "sbt-dotenv" % "3.1.1")
https://github.com/Philippus/sbt-dotenv/pull/129

2025-03-22 19:14 UTC, bjaglin commented on src/sbt-test/skip-sbt1.4/testkit/project/plugins.sbt
> +    Seq()
projectmatrix has been upstreamed (with package name changes)

2025-03-22 19:29 UTC, bjaglin commented on src/sbt-test/skip-windows/relax-scalacOptions/build.sbt
>  val V = _root_.scalafix.sbt.BuildInfo
This is moved to skip-windows because the last check `checkLastCompilationCached` (L46) fails on windows CI.

I suspect this is related to https://github.com/sbt/sbt/issues/7656 - even though a workaround was deployed, I don't see any cache hit on windows CI.

That said, the scripted should still work without remote cache, so there is something fishy. We can see from the logs that there is a spurious recompilation because the last one available on disk seems to come from L12, without `-Xfatal-warnings`.


```diff
 [info] [error] [debug] Found differing options:
-[info] [error] [debug] a: scala=-Ywarn-unused,just_to_invalidate_any_cache,-Xplugin:C:\Users\runneradmin\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scalameta\semanticdb-scalac_2.12.20\4.13.1.1\semanticdb-scalac_2.12.20-4.13.1.1.jar,-Yrangepos,-P:semanticdb:targetroot:C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\target\out\jvm\scala-2.12.20\sbt_9f337f25\meta,-Wconf:cat=deprecation:e,-Wconf:src=scala/IgnoreWarning.scala:s,-Xfuture,-deprecation java=
+[info] [error] [debug] b: scala=-Ywarn-unused,just_to_invalidate_any_cache,-Xfatal-warnings,-Xplugin:C:\Users\runneradmin\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scalameta\semanticdb-scalac_2.12.20\4.13.1.1\semanticdb-scalac_2.12.20-4.13.1.1.jar,-Yrangepos,-P:semanticdb:targetroot:C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\target\out\jvm\scala-2.12.20\sbt_9f337f25\meta,-Wconf:cat=deprecation:e,-Wconf:src=scala/IgnoreWarning.scala:s,-Xfuture,-deprecation java=
```

<details>
  <summary>Full logs</summary>

```
[info] Running sbt-scalafix/relax-scalacOptions
 [info] [launcher] getting org.scala-sbt sbt 2.0.0-M4  (this may take some time)...
 [info] [launcher] getting Scala 3.6.4 (for sbt)...
[info] [info] Updated file C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\project\build.properties: set sbt.version to 2.0.0-M4
[info] [info] welcome to sbt 2.0.0-M4 (Temurin Java 1.8.0_442)
[info] [info] loading project definition from C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\project
[info] [info] set current project to sbt_9f337f25 (in build file:/C:/Users/runneradmin/AppData/Local/Temp/sbt_9f337f25/)
[info] [info] welcome to sbt 2.0.0-M4 (Temurin Java 1.8.0_442)
[info] [info] loading project definition from C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\project
[info] [info] set current project to sbt_9f337f25 (in build file:/C:/Users/runneradmin/AppData/Local/Temp/sbt_9f337f25/)
[info] [info] compiling 2 Scala sources to C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\target\out\jvm\scala-2.12.20\sbt_9f337f25\backend ...
[info] [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.20. Compiling...
[info] [info]   Compilation completed in 8.787s.
[info] [warn] C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\src\main\scala\UnusedImportAndProcedureSyntax.scala:3:12: Procedure syntax is deprecated. Convert procedure `main` to method by adding `: Unit =`.
[info] [warn]   def main {}
[info] [warn]            ^
[info] [warn] C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\src\main\scala\UnusedImportAndProcedureSyntax.scala:2:20: Unused import
[info] [warn]   import java.util.Calendar
[info] [warn]                    ^
[info] [warn] two warnings found
[info] [info] done compiling
[info] [info] Running scalafix on 2 Scala sources
[info] [error] --- C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\src\main\scala\UnusedImportAndProcedureSyntax.scala
[info] [error] +++ <expected fix>
[info] [error] @@ -1,4 +1,3 @@
[info] [error]  object UnusedImportAndProcedureSyntax {
[info] [error] -  import java.util.Calendar
[info] [error]    def main {}
[info] [error]  }
[info] [error] (Compile / scalafix) scalafix.sbt.ScalafixFailed: TestError
[info] [error] elapsed time: 15 s, cache 0%, 2 onsite tasks
[info] [error] [debug] [zinc] IncrementalCompile -----------
[info] [error] [debug] IncrementalCompile.incrementalCompile
[info] [error] [debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[info] [error] [debug] current source = Set(${BASE}/src/main/scala/IgnoreWarning.scala, ${BASE}/src/main/scala/UnusedImportAndProcedureSyntax.scala)
[info] [error] [debug] > initialChanges = InitialChanges(Changes(added = Set(${BASE}/src/main/scala/UnusedImportAndProcedureSyntax.scala, ${BASE}/src/main/scala/IgnoreWarning.scala), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[info] [error] [debug] Full compilation, no sources in previous analysis.
[info] [error] [debug] all 2 sources are invalidated
[info] [error] [debug] Initial set of included nodes: 
[info] [error] [debug] Recompiling all sources: number of invalidated sources > 50.0 percent of all sources
[info] [error] [debug] compilation cycle 1
[info] [error] [info] compiling 2 Scala sources to C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\target\out\jvm\scala-2.12.20\sbt_9f337f25\backend ...
[info] [error] [debug] Getting org.scala-sbt:compiler-bridge_2.12:2.0.0-M3:compile for Scala 2.12.20
[info] [error] [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.20. Compiling...
[info] [error] [debug] Creating plain compiler interface for 2.12.20.
[info] [info] [debug] IncrementalCompile.incrementalCompile
[info] [info] [debug] previous = Stamps for: 4 products, 2 sources, 1 libraries
[info] [info] [debug] current source = Set(${BASE}/src/main/scala/IgnoreWarning.scala, ${BASE}/src/main/scala/UnusedImportAndProcedureSyntax.scala)
[info] [info] [debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[info] [info] [debug] No changes
[info] [info] [debug] wrote ${OUT}/jvm/scala-2.12.20/sbt_9f337f25/backend
[info] [success] elapsed time: 0 s
[info] [info] compiling 2 Scala sources to C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\target\out\jvm\scala-2.12.20\sbt_9f337f25\backend ...
[info] [info] done compiling
[info] [success] elapsed time: 1 s, cache 0%, 1 onsite task
[info] [error] [debug] Found differing options:
[info] [error] [debug] a: scala=-Ywarn-unused,just_to_invalidate_any_cache,-Xplugin:C:\Users\runneradmin\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scalameta\semanticdb-scalac_2.12.20\4.13.1.1\semanticdb-scalac_2.12.20-4.13.1.1.jar,-Yrangepos,-P:semanticdb:targetroot:C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\target\out\jvm\scala-2.12.20\sbt_9f337f25\meta,-Wconf:cat=deprecation:e,-Wconf:src=scala/IgnoreWarning.scala:s,-Xfuture,-deprecation java=
[info] [error] [debug] b: scala=-Ywarn-unused,just_to_invalidate_any_cache,-Xfatal-warnings,-Xplugin:C:\Users\runneradmin\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scalameta\semanticdb-scalac_2.12.20\4.13.1.1\semanticdb-scalac_2.12.20-4.13.1.1.jar,-Yrangepos,-P:semanticdb:targetroot:C:\Users\runneradmin\AppData\Local\Temp\sbt_9f337f25\target\out\jvm\scala-2.12.20\sbt_9f337f25\meta,-Wconf:cat=deprecation:e,-Wconf:src=scala/IgnoreWarning.scala:s,-Xfuture,-deprecation java=
[info] [error] [debug] [zinc] IncrementalCompile -----------
[info] [error] [debug] IncrementalCompile.incrementalCompile
[info] [error] [debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[info] [error] [debug] current source = Set(${BASE}/src/main/scala/IgnoreWarning.scala, ${BASE}/src/main/scala/UnusedImportAndProcedureSyntax.scala)
[info] [error] [debug] > initialChanges = InitialChanges(Changes(added = Set(${BASE}/src/main/scala/UnusedImportAndProcedureSyntax.scala, ${BASE}/src/main/scala/IgnoreWarning.scala), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[info] [error] [debug] Full compilation, no sources in previous analysis.
[info] [error] [debug] all 2 sources are invalidated
[info] [error] [debug] Initial set of included nodes: 
[info] [error] [debug] Recompiling all sources: number of invalidated sources > 50.0 percent of all s [...]

2025-03-22 19:42 UTC, merged

2025-03-22 20:09 UTC, bjaglin commented
This was [backpublished as 0.14.2](https://github.com/scalacenter/sbt-scalafix/releases/tag/v0.14.2%403.x%23sbt2.0.0-M4) using https://eed3si9n.com/tag-based-back-publishing-with-sbt.